#!/usr/bin/env bash
#
# Listen to ntfy.sh topic for the Kaggle tunnel URL.
# Once received: write to .env.local + restart Next.js dev server.
#
# Run this in a terminal AFTER you click "Run All" in the Kaggle notebook.
# It blocks until URL arrives.

set -e

TOPIC="davoai-tunnel-temur1210"
PROJECT="/Users/temur/Desktop/Claude/Hackathon_2/davo-ai/packages/dashboard"
ENV_FILE="${PROJECT}/.env.local"

echo "📡 Listening to ntfy.sh/${TOPIC} for tunnel URL..."
echo "    (Click 'Run All' in your Kaggle notebook to trigger)"
echo

# Use the JSON streaming endpoint and parse out 'message' field
URL=$(curl -sN "https://ntfy.sh/${TOPIC}/json" | \
  while IFS= read -r line; do
    msg=$(echo "$line" | python3 -c "import sys, json; d=json.loads(sys.stdin.read()); print(d.get('message','')) if d.get('event')=='message' else None" 2>/dev/null)
    if [[ "$msg" == https://* ]]; then
      echo "$msg"
      break
    fi
  done | head -n 1)

if [[ -z "$URL" ]]; then
  echo "✗ No URL received"
  exit 1
fi

echo
echo "✅ Got URL: $URL"
echo

# Write to .env.local
cat > "$ENV_FILE" <<EOF
# Auto-generated by listen-tunnel.sh on $(date)
NEXT_PUBLIC_KAGGLE_INFERENCE_URL=${URL}
EOF
echo "✏️  Wrote to ${ENV_FILE}:"
cat "$ENV_FILE"
echo

# Try to restart dev server (kill port 3001 if running)
PID=$(lsof -ti :3001 2>/dev/null || true)
if [[ -n "$PID" ]]; then
  echo "🔄 Killing dev server PID $PID (port 3001)..."
  kill "$PID" 2>/dev/null || true
  sleep 1
fi
echo "🚀 Starting dev server..."
cd "$PROJECT"
nohup pnpm dev > /tmp/dev.log 2>&1 &
echo "    Dev server PID: $!"
sleep 4
curl -s -o /dev/null -w "   /uz/today: HTTP %{http_code}\n" http://localhost:3001/uz/today

echo
echo "✅ Done. App is now using real Kaggle inference."
echo "    Open: http://localhost:3001/uz"
